# Extended Discussion  

The current study investigated personalized, idiographic prediction models for two behaviors, feeling lonely and procrastinating. Rather than assuming that antecedents of different outcomes were shared, our idiographic approach built N=1, personalized prediction models. Overall, three main conclusions emerged: First, psychological, situational, and time variables accurately predicted future everyday behaviors. Second, psychological and situational variables were both important, almost equally so, with neither being a predominant antecedent of behavior. Third, individual differences reigned supreme –people differed on how predictable outcomes were, which domains performed best, and which features were most important. These findings indicate the utility of an idiographic approach to psychological assessment relative to standard between-person approaches that are routinely used.  

## On predicting more behaviors more of the time  
We found accurate out-of-sample prediction of procrastination and feelings of loneliness when using a suite of personality and situational factors. While there are between-person individual differences in both loneliness and procrastination, there was also within-person variability in terms of how and when people experienced these behaviors. Typical prediction models within psychology have largely focused on which between-person features predict life outcomes or other aggregated behaviors (e.g., Beck & Jackson, 2021a; Joel et al., 2020; Puterman et al., 2020). Here, in alignment with a growing emphasis on precision medicine approaches to improving physical health, well-being, and productivity, we demonstrate that within-person features are also predictable by psychological and situation features. These dynamic features tend to be less studied, which has resulted in little knowledge about why people vary within-person in these behaviors. Our findings suggest that from a fairly prescribed set of personality, situational, and time features, we can identify when someone is going to procrastinate or feel lonely at a future timepoint – not just if they tend to procrastinate or feel lonely in general.   

Notably, predictions were made assuming individuals have unique antecedents of each behavior. Although this equifinality is often described in theoretical models, it is rarely implemented in statistical models. Instead, statistical models use a circumscribed set of predictors that are assumed to impact people similarly, depending on their rank-order on the predictor (e.g., Borsboom et al., 2003). For example, procrastination is associated with Conscientiousness (Jackson et al., 2009). Typically, this suggests if people are feeling low in Conscientiousness markers (responsibility, organization) they would be more likely to procrastinate. However, we found that markers of Conscientiousness were not important antecedents of procrastinating for everyone, nor were they the most important in general (with 10-15% of the sample having Conscientiousness features as important predictors). People both procrastinate and feel lonely for many different reasons. As a result, prediction models that assume similar associations between predictors and outcomes for everyone may underestimate potential predictive validity.  

In general, we found individual differences in every aspect of the models – in accuracy, in feature sets, and in the importance of specific features. For some people, we could highly accurately predict future behaviors, while for others, we could not. Similarly, people differed in which and the degree to which the domains were important. Together these findings paint a picture of a psychological system that is highly unique to an individual. Although there is a longstanding consensus that behavior is the output of such highly unique dynamic psychological systems that are impacted by situational features (Mischel & Shoda, 1995), these have remained elusive and often ignored in practice. Thus, the present study is an initial demonstrate of the empirical validity of such thinking. These participants demonstrated unique important situational and psychological features predicted future behavior.  

## The person situation debate revisited   

Half a century ago, the seeming limits of behavioral prediction that sparked the Person-Situation Debate and led to research being formulated around the question of whether person or situation features matter more. While most agree that both matter, there are few examples of demonstrating the joint importance of them for the same outcome (c.f., Sherman et al., 2015). We found evidence that person and situation features were both important for most individuals, with only a minority demonstrating that person or situation features alone were most predictive of future procrastination or loneliness. In other words, the Person-Situation Debate was always a false debate. The dynamic relations among person, situation, and behavior and indicate that attempts to understand behavior must incorporate both (Funder, 2006) – at least for most people.  

Not only are person and situation variables important, but they were also more important than time variables. Given that people have natural cycles of behavior that are regimented by time of day and day of week (Mathews, 1988; Larson, 1985), it would be natural to expect that behavior largely varies within and across people as a function of these cycles. For example, people work (behavior) less on the weekends and at night, which is a change their behavior. Similarly, time of day and day of week govern situations people can enter. Why were time variables not that important? It is likely that these time indices were already captured by the more proximal person or situational features. Time is likely important, but works through person and situation variables rather than being a separate factor.  

## Limitations and Conclusion  
This study is not without its limitations. First, relatively low variance in procrastination and loneliness led us to drop a number of participants from analyses. Thus, the participants in the present study are only representative of participants who experienced somewhat frequent loneliness and procrastination. Second, we examined prediction over a two week interval for most participants, so long-term prediction accuracy is unclear. Finally, we demonstrated high accuracy and AUC on average when predicting behavior four hours in the future, making it unclear how such models perform at different time intervals. However, given that processes unfold at different speeds both within- and between-person, model performance likely varies as a function of interval.  

The current study created personalized prediction models to help understand antecedents of future loneliness and procrastination. We found psychological and situational predictors did well in predicting within-person variations in these behaviors. However, in contrast to many years of methodological orthodoxy, the antecedents of these behaviors differed greatly across people. Thus, there is a need for more personalized assessments – not just longer assessments – but assessments that are tailored and important for the individual. Behavior appears to be highly predictable, so our next task is identifying personalized antecedents.  
